apiVersion: v1
kind: Service
metadata:
  annotations: 
{{ .Values.global.annotations | toYaml | indent 4}}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
  type: ClusterIP